### ISSUE TITLE
Branch release/public-v1 needs to be updated

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/EMC_crtm#14]
For some reason, release/public-v1 is not the same as the hash stored in the NCEPLIBS umbrella build. We should force-update release/public-v1 to hash cb01f17b71b366dfdb483dac4c1cecadf9d4c0ca, which is already tagged as ufs-v1.1.0 and works on all platforms supported for UFS MRW v1.1.0.

I don't have permissions to do that.

**Comment by climbfuji** [comment]
@aerorahul @kgerheiser can one of you please force-update branch release/public-v1 to hash cb01f17 = tag ufs-v1.1.0? Thanks ...

**Comment by kgerheiser** [comment]
Yes

**Comment by kgerheiser** [comment]
No, I can't. I also don't have permission. It's a protected branch.

**Comment by climbfuji** [comment]
Thanks for trying. We can either unprotect it briefly for this purpose, or I can try to create a PR to forward/reverse it to that hash.

**Comment by aerorahul** [comment]
I’ll do it tonight. Sorry for the delay.

**Comment by aerorahul** [comment]
I am sitting on `HEAD` of `release/public-v1` and this is what I see:
```
~/s/N/emc_crtm ❯❯❯ git lg                                                         release/public-v1
* dfbbcca - 2020-06-15 (3 months ago) <Rahul Mahajan> (HEAD -> release/public-v1, origin/release/public-v1) cmake package (#8)
*   cb01f17 - 2020-02-29 (6 months ago) <Mark Potts> (tag: ufs-v1.1.0) Merge pull request #6 from aerorahul/feature/cleanup
```

@climbfuji you want me to do what now? force `release/public-v1` to be the same as `ufs-v1.1.0`?

```
~/s/N/emc_crtm ❯❯❯ git reset --hard cb01f17

~/s/N/emc_crtm ❯❯❯ git status                                                                                                             release/public-v1 ⬇
On branch release/public-v1
Your branch is behind 'origin/release/public-v1' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean

~/s/N/emc_crtm ❯❯❯ git push --force                                                                                                       release/public-v1 ⬇
Total 0 (delta 0), reused 0 (delta 0)
remote: This repository moved. Please use the new location:
remote:   https://github.com/NOAA-EMC/EMC_crtm.git
remote: error: GH006: Protected branch update failed for refs/heads/release/public-v1.
remote: error: Cannot force-push to this protected branch
To https://github.com/NOAA-EMC/emc_crtm
 ! [remote rejected] release/public-v1 -> release/public-v1 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/NOAA-EMC/emc_crtm'
```

Looks like we have to remove protected status of `release/public-v1` first.

**Comment by climbfuji** [comment]
> I am sitting on `HEAD` of `release/public-v1` and this is what I see:
> 
> ```
> ~/s/N/emc_crtm ❯❯❯ git lg                                                         release/public-v1
> * dfbbcca - 2020-06-15 (3 months ago) <Rahul Mahajan> (HEAD -> release/public-v1, origin/release/public-v1) cmake package (#8)
> *   cb01f17 - 2020-02-29 (6 months ago) <Mark Potts> (tag: ufs-v1.1.0) Merge pull request #6 from aerorahul/feature/cleanup
> ```
> 
> @climbfuji you want me to do what now? force `release/public-v1` to be the same as `ufs-v1.1.0`?
> 
> ```
> ~/s/N/emc_crtm ❯❯❯ git reset --hard cb01f17
> 
> ~/s/N/emc_crtm ❯❯❯ git status                                                                                                             release/public-v1 ⬇
> On branch release/public-v1
> Your branch is behind 'origin/release/public-v1' by 1 commit, and can be fast-forwarded.
>   (use "git pull" to update your local branch)
> 
> nothing to commit, working tree clean
> 
> ~/s/N/emc_crtm ❯❯❯ git push --force                                                                                                       release/public-v1 ⬇
> Total 0 (delta 0), reused 0 (delta 0)
> remote: This repository moved. Please use the new location:
> remote:   https://github.com/NOAA-EMC/EMC_crtm.git
> remote: error: GH006: Protected branch update failed for refs/heads/release/public-v1.
> remote: error: Cannot force-push to this protected branch
> To https://github.com/NOAA-EMC/emc_crtm
>  ! [remote rejected] release/public-v1 -> release/public-v1 (protected branch hook declined)
> error: failed to push some refs to 'https://github.com/NOAA-EMC/emc_crtm'
> ```
> 
> Looks like we have to remove protected status of `release/public-v1` first.

Yes, release/public-v1 should point to the same hash as tag ufs-v1.1.0. We'll have to temporarily remove the branch protection. Thanks for your help!

**Comment by aerorahul** [comment]
@climbfuji done. Please check.

**Comment by climbfuji** [comment]
Perfect, thanks very much!
