### ISSUE TITLE
CRTM licensing and future distribution plans

### ISSUE THREAD

**Issue by BenjaminTJohnson** [NOAA-EMC/EMC_crtm#15]
@climbfuji  @mark-a-potts 
Dom, Mark:

In October 2020, JCSDA will make a public git-based release repository for CRTM (and JEDI), which will supersede all standalone repositories such as this one.   I will work with Mark to create a fork of the repository and establish to establish a build link with EMC folks, at that time we should be able to remove this repository altogether or change it to be a fork of the public release repository if necessary

Also, the licensing will also become unified across JCSDA projects, and will much more permissive at that time (looks like CC0 + Apache 2.0 right now) , the details are TBD.  

Nothing specific needs to be done here, just as an FYI.   If there will be further changes to this repository that need to be reflected in a CRTM release for EMC, please contact me directly with your requirements.    I have already created a private release repository for EMC available from: <git-lfs clone -b release/REL-2.3.0_emc https://github.com/JCSDA/CRTM_dev crtm_v230>

I will be generally permissive in granting read access to the repository until we go public.

-Ben (bjohns@ucar.edu)

**Comment by climbfuji** [comment]
Thanks for the heads up, @BenjaminTJohnson / Ben. I'd be interesting in getting read access to the repository before it goes public. Thanks!

**Comment by BenjaminTJohnson** [comment]
Done.

Just to orient you:  JCSDA/CRTM_dev is our main development repository. The
CRTM most people are familiar with is what exists below the src/Build
directory typically.   Here's a quick script that you could use to create a
build.

#!/bin/sh


source configuration/gfortran.setup

source Set_CRTM_Environment.sh

cd scripts/shell

./crtm_install_scripts.sh

cd Utility

./crtm_rebuild.sh


CRTM_dev contains the entire code history of the CRTM project, going back
to 2006, and there are lots of dead branches that need to be pruned. :)

We use git flow type branch structures.   I needed a way to make releases
available in the exact same format as what folks normally use, so I created
a release/  branch where the various release versions are kept, including
the requisite binary files (git-lfs stored).   All new user creations are
created under feature branches  e.g., feature/btj_newthing

You may wish to look at release/REL-2.3.0_emc and identify any missing
items compared to the modifications you've made on NOAA--EMC/EMC_crtm (It's
not clear to me where that's even being used).

Happy to set up a discussion any time or answer questions / take
recommendations.

Cheers,

-Ben

**Comment by climbfuji** [comment]
Thanks, Ben. Let's wait for Mark and the other experts before we set up a meeting.

**Comment by edwardhartnett** [comment]
@BenjaminTJohnson where is the repo that holds this code? When I point to the repo given above, I get a 404 not found error...

**Comment by BenjaminTJohnson** [comment]
Good morning:

We had an internal reorganization of our repositories in preparation for a
public release of several software packages, including CRTM.

I’ll get back to you tomorrow (Friday) with updated link(s) and discussion.


Cheers,

Ben

**Comment by edwardhartnett** [comment]
@BenjaminTJohnson any word on the state of your repository?
